name: Deploy Node Application

on:
  push:
    branches:
      - mern-ec2-docker

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t hafizahmedwaseem/nodejs-app .
      - name: Publish Image to docker hub
        run: docker push hafizahmedwaseem/nodejs-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps: 
      - name: Pull image from docker hub
        run: docker pull hafizahmedwaseem/nodejs-app:latest
      - name: Run Docker Container
        run: docker run -p 4000:4000 --name nodejs-app-container -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' hafizahmedwaseem/nodejs-app

